apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    app: {{ include "name" . }}
    helm.sh/chart: {{ include "chart-intro" . }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
    - port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
