apiVersion: skaffold/v1beta13
kind: Config

profiles:
  - name: default
    build:
      artifacts:
      - image: registry.cn-zhangjiakou.aliyuncs.com/cheerego/http
    deploy:
      helm:
        releases:
          - name: http-helm-default
            chartPath: http-helm
            namespace: default
            values:
              image.repository: registry.cn-zhangjiakou.aliyuncs.com/cheerego/http
            setValues:
              imagePullSecrets: cheerego
              service.port: 8080
              env.ENV: default
            setValueTemplates:   # 使用内置变量必须使用setValueTemplates
              image.repository: "{{ .IMAGE_NAME }}"
              image.tag: "{{ .DIGEST }}"